### PR TITLE
PyDarshan job summary cleanup fixes

### PR DESCRIPTION
**Pull request by shanedsnyder**
See #910 for more details.

This PR currently has fixes for:

- Captions are hard to read (light colored text, also italicized)
-  Add "% runtime" y-axis label to right-side of I/O cost plot
-  Offset autolabeling text at 45 degrees in access size histogram plot and POSIX access pattern plot as is done in I/O op count graph
-  Don't autolabel 0 values to further help with cluttering of plots
- add a forgotten space to our warning string when a log has no data

### CODE REVIEW

**Comment by tylerjereddy** [comment]
I'll try to take quick look tomorrow--I may try to draft a small testing class to enforce the changes that are easy to roundtrip-check from the produced html, and just label them as based on feedback from Argonne team.

**Review by tylerjereddy — COMMENTED** [review]
Seems sensible enough--here's a suggestion for some matching tests and a fix for the index name Argonne doesn't like. I avoided `read_html` because of the optional `lxml` test dep, although that is a more robust way to do round-trip parsing on tables in the report.

```diff
diff --git a/darshan-util/pydarshan/darshan/lib/accum.py b/darshan-util/pydarshan/darshan/lib/accum.py
index 924e69ee..d60fdecd 100644
--- a/darshan-util/pydarshan/darshan/lib/accum.py
+++ b/darshan-util/pydarshan/darshan/lib/accum.py
@@ -100,5 +100,6 @@ def log_file_count_summary_table(derived_metrics,
     df.drop(columns="index", inplace=True)
     ret = plot_common_access_table.DarshanReportTable(df,
                                                       col_space=200,
-                                                      justify="center")
+                                                      justify="center",
+                                                      index_names=False)
     return ret
diff --git a/darshan-util/pydarshan/darshan/tests/test_plot_exp_common.py b/darshan-util/pydarshan/darshan/tests/test_plot_exp_common.py
index 27b56aae..8e29828d 100644
--- a/darshan-util/pydarshan/darshan/tests/test_plot_exp_common.py
+++ b/darshan-util/pydarshan/darshan/tests/test_plot_exp_common.py
@@ -160,6 +160,12 @@ def test_xticks_and_labels(log_path, func, expected_xticklabels, mod):
 
     assert_array_equal(actual_xticks, expected_xticks)
     assert_array_equal(actual_xticklabels, expected_xticklabels)
+    # see Argonne formatting reqs in gh-910
+    spines = ax.spines
+    assert not spines["top"].get_visible()
+    assert not spines["right"].get_visible()
+    assert spines["bottom"].get_visible()
+    assert spines["left"].get_visible()
 
 
 @pytest.mark.parametrize(
diff --git a/darshan-util/pydarshan/darshan/tests/test_summary.py b/darshan-util/pydarshan/darshan/tests/test_summary.py
index 65832066..0dc9d2e3 100644
--- a/darshan-util/pydarshan/darshan/tests/test_summary.py
+++ b/darshan-util/pydarshan/darshan/tests/test_summary.py
@@ -21,6 +21,22 @@ except ImportError:
     has_lxml = False
 
 
+def _enforce_html_report_aesthetics(report_str):
+    # formatting requirements, partly from Argonne
+    # feedback in gh-910
+    prog = re.compile(r"figcaption {\n.*\n.*\n.*\n}")
+    m = prog.search(report_str)
+    if m:
+        result = m.group(0)
+    assert "font-weight: 300" in result
+    assert "font-size: 0.75em" in result
+    assert not "italic" in result
+
+    # Argonne team doesn't like index label
+    # for File Count Summary table
+    assert not "<th>type</th>" in report_str
+
+
 @pytest.mark.parametrize(
     "argv", [
         ["./tests/input/sample.darshan"],
@@ -187,6 +203,7 @@ def test_main_all_logs_repo_files(tmpdir, log_filepath):
             with darshan.DarshanReport(log_filepath, read_all=False) as report:
                 with open(expected_save_path) as html_report:
                     report_str = html_report.read()
+                    _enforce_html_report_aesthetics(report_str=report_str)
                     if "DXT" in "\t".join(report.modules):
                         for dxt_mod in ["DXT_POSIX", "DXT_MPIIO"]:
                             if dxt_mod in report.modules:
@@ -215,7 +232,7 @@ def test_main_all_logs_repo_files(tmpdir, log_filepath):
                             assert "Consider enabling the runtime heatmap module" in report_str
                         else:
                             # check empty log warning and return
-                            assert "This Darshan log file has no instrumentation records" in report_str
+                            assert "This Darshan log file has no instrumentation records, " in report_str
                             return
 
                     # check if I/O cost figure is present
```

**Comment by carns** [comment]
I like it.

The only other possibility would be to wrap the path to multiple lines (splitting on arbitrary characters) on the path name; we aren't lacking for vertical space.  I don't know if that's possible or not.   What you have is a good compromise.

**Comment by shanedsnyder** [comment]
> > The only other possibility would be to wrap the path to multiple lines (splitting on arbitrary characters) on the path name; we aren't lacking for vertical space. I don't know if that's possible or not. What you have is a good compromise.
> 
> I didn't try this, but after browsing around briefly it may be possible using matplotlib [`text`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.text.html) (`wrap` option). We are using `annotate` for this currently, but I think we could switch to `text` without issue (we are actually using it already for the byte and file count strings in this plot).
> 
> I'll tinker with it and see how it goes.

Eh, it's a little more complicated. This wrap option seems to only work on text with whitespace, which you won't get in an FS mount point. Not sure we'll have a lot of options for wrapping given that -- I don't see any example solutions looking around.

I think I'm just going to go with what we have for now.

That said, we may want to revisit in the future. I'm imagining what we'd put there for something like DAOS, which has quite long identifiers for pools/containers. It might be easiest to just: a) put the category name text in a dedicated, fixed-size subplot to the left of the 2 data subplots; b) be more aggressive about shortening category strings so they convey information and aren't arbitrarily chopped (e.g., "DAOS cont=...09zb", just showing the last 4 digits of the ID or something like that). We can worry more about that when it becomes an issue, I think.

**Comment by shanedsnyder** [comment]
I just committed some testing changes (including suggestions above from Tyler).

I think I'd like to stop any work on this PR and merge it in, and address remaining changes from #910 elsewhere (they are a little more involved and might warrant some discussion).

Note there are now some weird testing failures here when simply upgrading `pip`...

**Comment by tylerjereddy** [comment]
The M1 failure probably persists here b/c Cirrus perhaps doesn't auto-merge into `main` before running the tests. I think we just ignore that then. If the rest of the CI passes I'll just do a quick scan through.

**Comment by tylerjereddy** [comment]
Ok, I read through the diff one more time, spot checked the HTML report produced with `e3sm_io_heatmap_only.darshan`, and didn't see any issues. It sounds like the Argonne folks are in favor of most of these aesthetic adjustments so in it goes.

**Review by tylerjereddy — APPROVED** [review]

**Pull request merged**
