### PR TITLE
ENH: Update summary report figure captions

### PR DESCRIPTION
**Pull request by nawtrey**
* Update captions for DXT heat map, I/O cost, and Access Size
figures according to suggestions from Phil

* Contributes to issue #641

### CODE REVIEW

**Comment by nawtrey** [comment]
Here is an example report using `ior_hdf5_example.darshan`: [ior_report.tar.gz](https://github.com/darshan-hpc/darshan/files/7999124/ior_report.tar.gz)

**Comment by carns** [comment]
Slight correction from looking at the example: "broken down by process type" should probably be "broken down by access type" in the I/O Cost graph caption.

**Comment by nawtrey** [comment]
> Slight correction from looking at the example: "broken down by process type" should probably be "broken down by access type" in the I/O Cost graph caption.

Thanks, I'll fix this real quick

**Comment by tylerjereddy** [comment]
One point of caution--check the supported Python versions for the latest `pytest` release--we are bound to supporting some pretty old versions so that is something to consider before making changes, or to carefully guard changes based on Python version.

**Comment by tylerjereddy** [comment]
That said, test-time dependencies should be fair game to have a latest stable release--it is not really the same kind of burden as a bleeding-edge runtime dep.

**Review by tylerjereddy — APPROVED** [review]
Ok, I did a spot check of a report generated locally and Phil seems happy with the changes.

I checked off the corresponding items in the issue markdown list.

**Comment by tylerjereddy** [comment]
thanks

**Pull request merged**
