### PR TITLE
CI: setuptools pin for runtime job

### PR DESCRIPTION
**Pull request by tylerjereddy**
* try to circumvent gh-895 for now

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Revised to instead pin `pip` version for the runtime job--it looks likely that enforcement of new build system rules was deployed that `mpi4py` is not yet compliant with.

**Comment by tylerjereddy** [comment]
Ah, that doesn't work either, so it is perhaps the latest version of `setuptools` (Feb 1 new release) that needs to be pinned, though that's trickier to deal with as a dependency that may be specified indirectly through other deps.

**Comment by tylerjereddy** [comment]
I think the `setuptools` pin/fix here is more appropriate given the upstream discussion, and seems to work better locally with `act`, but now GHA is complaining about something unrelated: `E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/main/binary-amd64/Packages.gz  Hash Sum mismatch.`

Maybe best to try that later or tomorrow then...

**Comment by tylerjereddy** [comment]
Alright, the CI is passing now. It isn't exactly pretty, but you can see other projects adopting a similar solution in the linked upstream issue.

**Review by shanedsnyder — APPROVED** [review]

**Comment by shanedsnyder** [comment]
Sounds good, thanks for tracking that down!

**Pull request merged**
