### PR TITLE
Add "extra info" field to the records

### PR DESCRIPTION
**Pull request by shanedsnyder**
In GitLab by @roblatham00 on Feb 21, 2018, 14:45

I did this a while back on intel-hpdd's repo, where it seems to have been forgotten.

I have sometimes needed to annotate log fields with extra information.  for example, in ROMIO, it was helpful to know which round of two-phase collective I/O an operation happened in.

I suspect EXTRA_INFO would be used rarely, so adding 64 bytes to a log entry all the time seems wasteful.  Can switch to a more dynamic approach where EXTRA_INFO allocated only if environment variable set if that seems better

### CODE REVIEW

**Comment by shanedsnyder** [comment]
In GitLab by @carns on Feb 28, 2018, 13:04

I would vote for a dynamic approach for sure.  64 bytes per access is too much for the general case.

How do you use it exactly?  Do you just do putenv() in the code you are annotating to pass information that will show up in DXT?

In that case, maybe a doc update with the pull request too just so we can remember how to use it when needed :)

**Comment by shanedsnyder** [comment]
In GitLab by @roblatham00 on Apr 20, 2020, 10:38

added 152 commits

<ul><li>657de0d7...7dfbddce - 148 commits from branch <code>master</code></li><li>cf60c400 - Initialize arguments for MPI-IO check</li><li>6bd1cfea - fix a shadowed declaration warning</li><li>f9eab31e - add an &#39;offset&#39; to mpi-io traces</li><li>00304584 - update parser to show MPI-IO offset information</li></ul>

[Compare with previous version](/darshan/darshan/merge_requests/19/diffs?diff_id=8953&start_sha=657de0d7db873245c804525c16713c9c6c635c74)

**Comment by shanedsnyder** [comment]
In GitLab by @roblatham00 on May 1, 2020, 15:16

closed

**Comment by shanedsnyder** [comment]
In GitLab by @roblatham00 on May 1, 2020, 15:17

Uh looks like I force-pushed and overwrote these changes.  I'll have to find the old work and dust it off; might not even still be a good idea.

**Comment by roblatham00** [comment]
Not saying the idea is any good, but it wasn't a ton of work to update to main.

**Comment by roblatham00** [comment]
revisit this work in #979

**Pull request closed without merging**
