### PR TITLE
CI: add Python 3.6

### PR DESCRIPTION
**Pull request by tylerjereddy**
* there's a request from Kevin to support Python 3.6 for
now so add it to the CI (see: https://github.com/darshan-hpc/darshan/issues/419#issuecomment-930540108 )

* note that Python 3.6 will be EOL in just a few months:
https://devguide.python.org/#status-of-python-branches

* I suggest revisiting this in the near future, also
to keep our support surface manageable

### CODE REVIEW

**Comment by tylerjereddy** [comment]
@kevin-harms @carns note the CI failures here--supporting Python 3.6 through 3.10 is going to be a bit of work, so definitely make sure we need it. 3.6 will be EOL in just a few months.

We can probably make it work if need though.

**Comment by kevin-harms** [comment]
I took a look at some of the relevant systems we work on and 3.6 is the default on all systems so it would make a suitable baseline. If 3.6 becomes problematic, we could bump up to 3.8 as a minimum, but that means users on some systems will need to select a non-default python3.

**Comment by tylerjereddy** [comment]
Ok, just wanted confirmation, thanks

**Comment by tylerjereddy** [comment]
Ok, CI is passing with Python `3.6` added in. I will leave this open for comments/suggestions for a few days, then merge in to enforce the support requirements at Argonne. I'll also open an issue to remind us about what we can "restore" once we can ditch Python `3.6` support.

**Comment by tylerjereddy** [comment]
Ok, no further comments.. the crippling of our type hints to support 3.6 is most unfortunate, but I'll merge this in to support HPC requirements.

**Pull request merged**
